spring:
  application:
    name: spring-security-oauth-facebook

security:
  oauth2:
    client:
      clientId: <APP_ID>
      clientSecret: <APP_SECRET>
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me