spring:
  application:
    name: spring-security-oauth-facebook

security:
  oauth2:
    client:
      clientId: 350182259561466
      clientSecret: e7ef744040cf8ead612618d67bb265ea
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me